/* !!!!!!!! AUTOGENERATED !!!!!!! - do not modify the content of this file */

namespace Kafka.TopicSplitter.Contracts.Events.Order
{
   public partial class OrderCreated : IVersionedIntegrationEvent {}
}